std_msgs/Header header

yhs_can_interfaces/FwCtrlFb     ctrl_fb
yhs_can_interfaces/FwIoFb       io_fb

yhs_can_interfaces/FwLrWheelFb   lr_wheel_fb
yhs_can_interfaces/FwRrWheelFb   rr_wheel_fb

yhs_can_interfaces/FwLfWheelFb   lf_wheel_fb
yhs_can_interfaces/FwRfWheelFb   rf_wheel_fb

yhs_can_interfaces/FwFrontAngleFb      front_angle_fb 
yhs_can_interfaces/FwRearAngleFb      rear_angle_fb 

yhs_can_interfaces/FwBmsFlagFb  bms_flag_fb 
yhs_can_interfaces/FwBmsFb      bms_fb 
